from decimal import Decimal

from django.core.management.base import BaseCommand

from apps.accounts.models import Customer
from apps.catalog.models import Brand, Category, Product, ProductImage, Review, SubCategory

GST_BY_CATEGORY = {
    "audio": Decimal("18.00"),
    "charging": Decimal("18.00"),
    "accessories": Decimal("12.00"),
    "storage": Decimal("18.00"),
}


def seed_gst(item: dict) -> Decimal:
    if item.get("gst"):
        return Decimal(item["gst"])
    return GST_BY_CATEGORY.get(item["category"], Decimal("18.00"))


CATEGORIES = [
    ("Audio", "audio", [("Earbuds", "earbuds"), ("Headphones", "headphones"), ("Speakers", "speakers")]),
    ("Charging", "charging", [("Adapters", "adapters"), ("Power banks", "power-banks"), ("Cables", "cables")]),
    ("Accessories", "accessories", [("Hubs", "hubs"), ("Stands", "stands"), ("Cases", "cases")]),
    ("Storage", "storage", [("Drives", "drives")]),
]

BRANDS = [
    ("Nimbus", "nimbus"),
    ("Harbor", "harbor"),
    ("VoltPack", "voltpack"),
    ("SonicCharge", "soniccharge"),
    ("PortLink", "portlink"),
    ("FluxDrive", "fluxdrive"),
    ("PulseBand", "pulseband"),
    ("Typewell", "typewell"),
    ("RoomNote", "roomnote"),
    ("Glide", "glide"),
]

PRODUCTS = [
    {
        "name": "Nimbus Air Buds",
        "slug": "nimbus-air-buds",
        "sku": "NB-AIR-1",
        "brand": "nimbus",
        "category": "audio",
        "subcategory": "earbuds",
        "price": "599.00",
        "sale_price": "449.00",
        "short": "Compact wireless earbuds for daily commutes.",
        "featured": True,
        "best_seller": True,
        "stock": 42,
    },
    {
        "name": "Harbor Bass One Headphones",
        "slug": "harbor-bass-one",
        "sku": "HB-BASS-1",
        "brand": "harbor",
        "category": "audio",
        "subcategory": "headphones",
        "price": "899.00",
        "sale_price": "699.00",
        "short": "Over-ear headphones with deep, even bass.",
        "featured": True,
        "best_seller": True,
        "stock": 28,
    },
    {
        "name": "RoomNote Go Bluetooth Speaker",
        "slug": "roomnote-go",
        "sku": "RN-GO-1",
        "brand": "roomnote",
        "category": "audio",
        "subcategory": "speakers",
        "gst": "28.00",
        "price": "549.00",
        "sale_price": None,
        "short": "Portable speaker for desks and small rooms.",
        "featured": True,
        "best_seller": False,
        "stock": 35,
    },
    {
        "name": "VoltPack 10000mAh Power Bank",
        "slug": "voltpack-10k",
        "sku": "VP-10K-1",
        "brand": "voltpack",
        "category": "charging",
        "subcategory": "power-banks",
        "price": "449.00",
        "sale_price": "349.00",
        "short": "Slim 10,000 mAh pack with dual output.",
        "featured": False,
        "best_seller": True,
        "stock": 60,
    },
    {
        "name": "SonicCharge 33W Wall Adapter",
        "slug": "soniccharge-33w",
        "sku": "SC-33W-1",
        "brand": "soniccharge",
        "category": "charging",
        "subcategory": "adapters",
        "price": "299.00",
        "sale_price": "199.00",
        "short": "33W USB-C wall adapter for phones and earbuds.",
        "featured": True,
        "best_seller": False,
        "stock": 80,
    },
    {
        "name": "PortLink 7-in-1 USB Hub",
        "slug": "portlink-7",
        "sku": "PL-HUB-7",
        "brand": "portlink",
        "category": "accessories",
        "subcategory": "hubs",
        "price": "649.00",
        "sale_price": "499.00",
        "short": "HDMI, USB-A, and SD ports in one compact hub.",
        "featured": False,
        "best_seller": False,
        "stock": 40,
    },
    {
        "name": "PortLink Aluminum Laptop Stand",
        "slug": "portlink-stand",
        "sku": "PL-ST-1",
        "brand": "portlink",
        "category": "accessories",
        "subcategory": "stands",
        "price": "849.00",
        "sale_price": "699.00",
        "short": "Raised aluminum stand with airflow slots.",
        "featured": False,
        "best_seller": False,
        "stock": 22,
    },
    {
        "name": "FluxDrive 512GB Portable SSD",
        "slug": "fluxdrive-512",
        "sku": "FD-512-1",
        "brand": "fluxdrive",
        "category": "storage",
        "subcategory": "drives",
        "price": "949.00",
        "sale_price": "799.00",
        "short": "USB-C portable SSD for backups and edits.",
        "featured": False,
        "best_seller": True,
        "stock": 18,
    },
    {
        "name": "FluxDrive 1TB Portable SSD",
        "slug": "fluxdrive-1tb",
        "sku": "FD-1TB-1",
        "brand": "fluxdrive",
        "category": "storage",
        "subcategory": "drives",
        "price": "999.00",
        "sale_price": "899.00",
        "short": "1TB USB-C drive for photo and video libraries.",
        "featured": True,
        "best_seller": False,
        "stock": 14,
    },
    {
        "name": "Nimbus Clip Buds",
        "slug": "nimbus-clip-buds",
        "sku": "NB-CLIP-1",
        "brand": "nimbus",
        "category": "audio",
        "subcategory": "earbuds",
        "price": "399.00",
        "sale_price": "299.00",
        "short": "Lightweight clip-on earbuds for calls and commutes.",
        "featured": False,
        "best_seller": True,
        "stock": 70,
    },
    {
        "name": "Harbor Wired Earphones",
        "slug": "harbor-wired-earphones",
        "sku": "HB-WIRE-1",
        "brand": "harbor",
        "category": "audio",
        "subcategory": "earbuds",
        "price": "199.00",
        "sale_price": "149.00",
        "short": "3.5mm earphones with a built-in mic.",
        "featured": False,
        "best_seller": False,
        "stock": 120,
    },
    {
        "name": "Nimbus Neckband SE",
        "slug": "nimbus-neckband-se",
        "sku": "NB-NECK-1",
        "brand": "nimbus",
        "category": "audio",
        "subcategory": "headphones",
        "price": "799.00",
        "sale_price": "649.00",
        "short": "Wireless neckband with 20-hour playback.",
        "featured": True,
        "best_seller": False,
        "stock": 44,
    },
    {
        "name": "RoomNote Mini Speaker",
        "slug": "roomnote-mini",
        "sku": "RN-MINI-1",
        "brand": "roomnote",
        "category": "audio",
        "subcategory": "speakers",
        "price": "349.00",
        "sale_price": "279.00",
        "short": "Palm-size Bluetooth speaker for travel.",
        "featured": False,
        "best_seller": False,
        "stock": 58,
    },
    {
        "name": "SonicCharge 20W Wall Adapter",
        "slug": "soniccharge-20w",
        "sku": "SC-20W-1",
        "brand": "soniccharge",
        "category": "charging",
        "subcategory": "adapters",
        "price": "199.00",
        "sale_price": "149.00",
        "short": "Compact 20W USB-C charger for phones.",
        "featured": False,
        "best_seller": True,
        "stock": 95,
    },
    {
        "name": "VoltPack 5000mAh Power Bank",
        "slug": "voltpack-5k",
        "sku": "VP-5K-1",
        "brand": "voltpack",
        "category": "charging",
        "subcategory": "power-banks",
        "price": "299.00",
        "sale_price": "249.00",
        "short": "Pocket 5,000 mAh pack for one extra charge.",
        "featured": False,
        "best_seller": False,
        "stock": 88,
    },
    {
        "name": "SonicCharge USB-C Cable 1m",
        "slug": "soniccharge-usbc-1m",
        "sku": "SC-CBL-1",
        "brand": "soniccharge",
        "category": "charging",
        "subcategory": "cables",
        "price": "179.00",
        "sale_price": "129.00",
        "short": "Braided 1 metre USB-C cable.",
        "featured": False,
        "best_seller": True,
        "stock": 150,
    },
    {
        "name": "SonicCharge USB-C Cable 2m",
        "slug": "soniccharge-usbc-2m",
        "sku": "SC-CBL-2",
        "brand": "soniccharge",
        "category": "charging",
        "subcategory": "cables",
        "price": "249.00",
        "sale_price": "179.00",
        "short": "Long braided USB-C cable for desks and sofas.",
        "featured": False,
        "best_seller": False,
        "stock": 110,
    },
    {
        "name": "VoltPack 20W Car Charger",
        "slug": "voltpack-car-20w",
        "sku": "VP-CAR-1",
        "brand": "voltpack",
        "category": "charging",
        "subcategory": "adapters",
        "price": "349.00",
        "sale_price": "279.00",
        "short": "Dual-port 20W car charger for road trips.",
        "featured": False,
        "best_seller": False,
        "stock": 64,
    },
    {
        "name": "SonicCharge 3-in-1 Charge Cable",
        "slug": "soniccharge-3in1",
        "sku": "SC-3IN1-1",
        "brand": "soniccharge",
        "category": "charging",
        "subcategory": "cables",
        "price": "299.00",
        "sale_price": "229.00",
        "short": "USB-C, Lightning, and micro-USB tips on one cable.",
        "featured": True,
        "best_seller": False,
        "stock": 72,
    },
    {
        "name": "PortLink 4-Port USB Hub",
        "slug": "portlink-4",
        "sku": "PL-HUB-4",
        "brand": "portlink",
        "category": "accessories",
        "subcategory": "hubs",
        "price": "349.00",
        "sale_price": "279.00",
        "short": "Four USB-A ports for keyboards and drives.",
        "featured": False,
        "best_seller": False,
        "stock": 66,
    },
    {
        "name": "PortLink Phone Stand",
        "slug": "portlink-phone-stand",
        "sku": "PL-PHST-1",
        "brand": "portlink",
        "category": "accessories",
        "subcategory": "stands",
        "price": "199.00",
        "sale_price": "149.00",
        "short": "Folding stand for video calls and recipes.",
        "featured": False,
        "best_seller": True,
        "stock": 90,
    },
    {
        "name": "PortLink Cable Clips 8-Pack",
        "slug": "portlink-cable-clips",
        "sku": "PL-CLIP-8",
        "brand": "portlink",
        "category": "accessories",
        "subcategory": "stands",
        "price": "149.00",
        "sale_price": "119.00",
        "short": "Adhesive clips to keep desk cables in place.",
        "featured": False,
        "best_seller": False,
        "stock": 140,
    },
    {
        "name": "PortLink 14-inch Laptop Sleeve",
        "slug": "portlink-sleeve-14",
        "sku": "PL-SLV-14",
        "brand": "portlink",
        "category": "accessories",
        "subcategory": "cases",
        "price": "599.00",
        "sale_price": "449.00",
        "short": "Padded sleeve for 13-inch and 14-inch laptops.",
        "featured": False,
        "best_seller": False,
        "stock": 38,
    },
    {
        "name": "Glide Silicone Cable Ties",
        "slug": "glide-cable-ties",
        "sku": "GL-TIE-1",
        "brand": "glide",
        "category": "accessories",
        "subcategory": "cases",
        "price": "129.00",
        "sale_price": "109.00",
        "short": "Reusable ties for chargers and earphones.",
        "featured": False,
        "best_seller": False,
        "stock": 160,
    },
    {
        "name": "FluxDrive 64GB USB Drive",
        "slug": "fluxdrive-64",
        "sku": "FD-USB-64",
        "brand": "fluxdrive",
        "category": "storage",
        "subcategory": "drives",
        "price": "199.00",
        "sale_price": "149.00",
        "short": "Metal 64GB USB-A drive for documents.",
        "featured": False,
        "best_seller": False,
        "stock": 100,
    },
    {
        "name": "FluxDrive 128GB USB Drive",
        "slug": "fluxdrive-128",
        "sku": "FD-USB-128",
        "brand": "fluxdrive",
        "category": "storage",
        "subcategory": "drives",
        "price": "299.00",
        "sale_price": "229.00",
        "short": "128GB USB-A drive for classwork and backups.",
        "featured": False,
        "best_seller": True,
        "stock": 84,
    },
    {
        "name": "FluxDrive 256GB USB Drive",
        "slug": "fluxdrive-256",
        "sku": "FD-USB-256",
        "brand": "fluxdrive",
        "category": "storage",
        "subcategory": "drives",
        "price": "449.00",
        "sale_price": "349.00",
        "short": "256GB drive for photos and offline files.",
        "featured": True,
        "best_seller": False,
        "stock": 52,
    },
    {
        "name": "FluxDrive Card Reader",
        "slug": "fluxdrive-card-reader",
        "sku": "FD-CR-1",
        "brand": "fluxdrive",
        "category": "storage",
        "subcategory": "drives",
        "price": "249.00",
        "sale_price": "199.00",
        "short": "USB-C reader for SD and microSD cards.",
        "featured": False,
        "best_seller": False,
        "stock": 76,
        "image": "fluxdrive-512",
    },
    # Extra Audio
    {
        "name": "Nimbus Sport Buds Pro",
        "slug": "nimbus-sport-buds-pro",
        "sku": "NB-SPT-1",
        "brand": "nimbus",
        "category": "audio",
        "subcategory": "earbuds",
        "price": "749.00",
        "sale_price": "599.00",
        "short": "Sweat-ready earbuds with secure wing tips.",
        "featured": True,
        "best_seller": False,
        "stock": 48,
        "image": "nimbus-air-buds",
    },
    {
        "name": "Harbor Studio Pro Headphones",
        "slug": "harbor-studio-pro",
        "sku": "HB-STD-1",
        "brand": "harbor",
        "category": "audio",
        "subcategory": "headphones",
        "price": "999.00",
        "sale_price": "849.00",
        "short": "Closed-back headphones for focused listening.",
        "featured": False,
        "best_seller": True,
        "stock": 26,
        "image": "harbor-bass-one",
    },
    {
        "name": "RoomNote Boom Party Speaker",
        "slug": "roomnote-boom",
        "sku": "RN-BOOM-1",
        "brand": "roomnote",
        "category": "audio",
        "subcategory": "speakers",
        "gst": "28.00",
        "price": "899.00",
        "sale_price": "749.00",
        "short": "Louder portable speaker with pair mode.",
        "featured": True,
        "best_seller": False,
        "stock": 31,
        "image": "roomnote-go",
    },
    {
        "name": "Harbor Kids Safe Headphones",
        "slug": "harbor-kids-headphones",
        "sku": "HB-KID-1",
        "brand": "harbor",
        "category": "audio",
        "subcategory": "headphones",
        "price": "499.00",
        "sale_price": "399.00",
        "short": "Volume-limited over-ears for younger listeners.",
        "featured": False,
        "best_seller": False,
        "stock": 55,
        "image": "harbor-bass-one",
    },
    {
        "name": "Nimbus Twin Buds Pack",
        "slug": "nimbus-twin-buds-pack",
        "sku": "NB-TWIN-1",
        "brand": "nimbus",
        "category": "audio",
        "subcategory": "earbuds",
        "price": "999.00",
        "sale_price": "799.00",
        "short": "Two Air Buds sets for home and office.",
        "featured": False,
        "best_seller": False,
        "stock": 20,
        "image": "nimbus-air-buds",
    },
    # Extra Charging
    {
        "name": "VoltPack 20000mAh Power Bank",
        "slug": "voltpack-20k",
        "sku": "VP-20K-1",
        "brand": "voltpack",
        "category": "charging",
        "subcategory": "power-banks",
        "price": "899.00",
        "sale_price": "749.00",
        "short": "High-capacity pack for multi-device travel days.",
        "featured": True,
        "best_seller": True,
        "stock": 36,
        "image": "voltpack-10k",
    },
    {
        "name": "SonicCharge 65W GaN Adapter",
        "slug": "soniccharge-65w",
        "sku": "SC-65W-1",
        "brand": "soniccharge",
        "category": "charging",
        "subcategory": "adapters",
        "price": "999.00",
        "sale_price": "849.00",
        "short": "Compact GaN charger for phones and light laptops.",
        "featured": True,
        "best_seller": False,
        "stock": 29,
        "image": "soniccharge-33w",
    },
    {
        "name": "VoltPack Mag Wireless Bank",
        "slug": "voltpack-mag-bank",
        "sku": "VP-MAG-1",
        "brand": "voltpack",
        "category": "charging",
        "subcategory": "power-banks",
        "price": "799.00",
        "sale_price": "649.00",
        "short": "Magnetic wireless pack for snap-on top-ups.",
        "featured": False,
        "best_seller": False,
        "stock": 41,
        "image": "voltpack-10k",
    },
    {
        "name": "SonicCharge Dual USB Wall Adapter",
        "slug": "soniccharge-dual-wall",
        "sku": "SC-DUAL-1",
        "brand": "soniccharge",
        "category": "charging",
        "subcategory": "adapters",
        "price": "349.00",
        "sale_price": "279.00",
        "short": "USB-A and USB-C ports in one wall brick.",
        "featured": False,
        "best_seller": True,
        "stock": 78,
        "image": "soniccharge-33w",
    },
    {
        "name": "SonicCharge Braided Lightning Cable",
        "slug": "soniccharge-lightning-1m",
        "sku": "SC-LTG-1",
        "brand": "soniccharge",
        "category": "charging",
        "subcategory": "cables",
        "price": "229.00",
        "sale_price": "169.00",
        "short": "Durable 1 metre Lightning charge cable.",
        "featured": False,
        "best_seller": False,
        "stock": 125,
        "image": "soniccharge-33w",
    },
    # Extra Accessories
    {
        "name": "PortLink Desk Dock 8-in-1",
        "slug": "portlink-desk-dock",
        "sku": "PL-DOCK-8",
        "brand": "portlink",
        "category": "accessories",
        "subcategory": "hubs",
        "price": "999.00",
        "sale_price": "849.00",
        "short": "Desktop dock with HDMI, ethernet, and USB ports.",
        "featured": True,
        "best_seller": False,
        "stock": 24,
        "image": "portlink-7",
    },
    {
        "name": "PortLink Monitor Riser Stand",
        "slug": "portlink-monitor-riser",
        "sku": "PL-MON-1",
        "brand": "portlink",
        "category": "accessories",
        "subcategory": "stands",
        "price": "799.00",
        "sale_price": "649.00",
        "short": "Wood-look riser with under-desk storage space.",
        "featured": False,
        "best_seller": True,
        "stock": 33,
        "image": "portlink-stand",
    },
    {
        "name": "PortLink Soft Laptop Sleeve 15",
        "slug": "portlink-sleeve-15",
        "sku": "PL-SLV-15",
        "brand": "portlink",
        "category": "accessories",
        "subcategory": "cases",
        "price": "699.00",
        "sale_price": "549.00",
        "short": "Padded sleeve for 15-inch and 16-inch laptops.",
        "featured": False,
        "best_seller": False,
        "stock": 27,
        "image": "portlink-stand",
    },
    {
        "name": "Glide Desk Mat XL",
        "slug": "glide-desk-mat",
        "sku": "GL-MAT-1",
        "brand": "glide",
        "category": "accessories",
        "subcategory": "stands",
        "price": "449.00",
        "sale_price": "349.00",
        "short": "Wide desk mat for keyboard, mouse, and notes.",
        "featured": False,
        "best_seller": False,
        "stock": 62,
        "image": "glide-silent",
    },
    {
        "name": "PortLink Travel Cable Pouch",
        "slug": "portlink-travel-pouch",
        "sku": "PL-POUCH-1",
        "brand": "portlink",
        "category": "accessories",
        "subcategory": "cases",
        "price": "299.00",
        "sale_price": "229.00",
        "short": "Zip pouch for chargers, earbuds, and cards.",
        "featured": True,
        "best_seller": False,
        "stock": 74,
        "image": "portlink-7",
    },
    # Extra Storage
    {
        "name": "FluxDrive 2TB Portable SSD",
        "slug": "fluxdrive-2tb",
        "sku": "FD-2TB-1",
        "brand": "fluxdrive",
        "category": "storage",
        "subcategory": "drives",
        "price": "999.00",
        "sale_price": "949.00",
        "short": "2TB USB-C SSD for large media libraries.",
        "featured": True,
        "best_seller": True,
        "stock": 12,
        "image": "fluxdrive-1tb",
    },
    {
        "name": "FluxDrive MicroSD 128GB",
        "slug": "fluxdrive-microsd-128",
        "sku": "FD-MSD-128",
        "brand": "fluxdrive",
        "category": "storage",
        "subcategory": "drives",
        "price": "399.00",
        "sale_price": "319.00",
        "short": "A2 microSD card for phones and action cams.",
        "featured": False,
        "best_seller": True,
        "stock": 90,
        "image": "fluxdrive-512",
    },
    {
        "name": "FluxDrive MicroSD 256GB",
        "slug": "fluxdrive-microsd-256",
        "sku": "FD-MSD-256",
        "brand": "fluxdrive",
        "category": "storage",
        "subcategory": "drives",
        "price": "649.00",
        "sale_price": "529.00",
        "short": "256GB microSD for 4K clips and offline maps.",
        "featured": False,
        "best_seller": False,
        "stock": 58,
        "image": "fluxdrive-512",
    },
    {
        "name": "FluxDrive 2.5-inch Enclosure",
        "slug": "fluxdrive-enclosure",
        "sku": "FD-ENC-1",
        "brand": "fluxdrive",
        "category": "storage",
        "subcategory": "drives",
        "price": "549.00",
        "sale_price": "429.00",
        "short": "USB-C enclosure for 2.5-inch SATA drives.",
        "featured": False,
        "best_seller": False,
        "stock": 39,
        "image": "fluxdrive-1tb",
    },
    {
        "name": "FluxDrive 32GB USB Drive",
        "slug": "fluxdrive-32",
        "sku": "FD-USB-32",
        "brand": "fluxdrive",
        "category": "storage",
        "subcategory": "drives",
        "price": "149.00",
        "sale_price": "119.00",
        "short": "Compact 32GB USB-A drive for everyday files.",
        "featured": False,
        "best_seller": False,
        "stock": 130,
        "image": "fluxdrive-512",
    },
]


# Existing JPG filenames in frontend/public/catalog used when a product has no dedicated asset.
IMAGE_FALLBACKS = {
    "nimbus-clip-buds": "nimbus-air-buds",
    "harbor-wired-earphones": "harbor-bass-one",
    "nimbus-neckband-se": "nimbus-air-buds",
    "roomnote-mini": "roomnote-go",
    "soniccharge-20w": "soniccharge-33w",
    "voltpack-5k": "voltpack-10k",
    "soniccharge-usbc-1m": "soniccharge-33w",
    "soniccharge-usbc-2m": "soniccharge-33w",
    "voltpack-car-20w": "voltpack-10k",
    "soniccharge-3in1": "soniccharge-33w",
    "portlink-4": "portlink-7",
    "portlink-phone-stand": "portlink-stand",
    "portlink-cable-clips": "portlink-stand",
    "portlink-sleeve-14": "portlink-stand",
    "glide-cable-ties": "glide-silent",
    "fluxdrive-64": "fluxdrive-512",
    "fluxdrive-128": "fluxdrive-512",
    "fluxdrive-256": "fluxdrive-512",
}


def catalog_image_url(item: dict) -> str:
    slug = item.get("image") or IMAGE_FALLBACKS.get(item["slug"], item["slug"])
    return f"/catalog/{slug}.jpg"


class Command(BaseCommand):
    help = "Create demo catalog records for the shop listing page."

    def handle(self, *args, **options):
        categories: dict[str, Category] = {}
        subcategories: dict[tuple[str, str], SubCategory] = {}
        brands: dict[str, Brand] = {}

        for name, slug, children in CATEGORIES:
            category, _ = Category.objects.update_or_create(
                slug=slug,
                defaults={"name": name, "is_active": True},
            )
            categories[slug] = category
            for child_name, child_slug in children:
                subcategory, _ = SubCategory.objects.update_or_create(
                    category=category,
                    slug=child_slug,
                    defaults={"name": child_name, "is_active": True},
                )
                subcategories[(slug, child_slug)] = subcategory

        for name, slug in BRANDS:
            brand, _ = Brand.objects.update_or_create(
                slug=slug,
                defaults={"name": name, "is_active": True},
            )
            brands[slug] = brand

        created = 0
        updated = 0
        for item in PRODUCTS:
            product, was_created = Product.objects.update_or_create(
                slug=item["slug"],
                defaults={
                    "name": item["name"],
                    "sku": item["sku"],
                    "description": item["short"],
                    "short_description": item["short"],
                    "brand": brands[item["brand"]],
                    "category": categories[item["category"]],
                    "subcategory": subcategories[(item["category"], item["subcategory"])],
                    "price": Decimal(item["price"]),
                    "sale_price": Decimal(item["sale_price"]) if item["sale_price"] else None,
                    "gst_percentage": seed_gst(item),
                    "stock_quantity": item["stock"],
                    "is_published": True,
                    "is_featured": item["featured"],
                    "is_best_seller": item["best_seller"],
                },
            )
            created += int(was_created)
            updated += int(not was_created)
            product.images.all().delete()
            ProductImage.objects.create(
                product=product,
                url=catalog_image_url(item),
                alt_text=f"{item['name']} product image",
                is_primary=True,
                sort_order=0,
            )

        reviewers = [
            ("Asha Verma", "asha.reviews@example.com", "9811111111"),
            ("Kiran Patel", "kiran.reviews@example.com", "9822222222"),
        ]
        customers = []
        for name, email, phone in reviewers:
            customer, _ = Customer.objects.update_or_create(
                email=email,
                defaults={"full_name": name, "phone": phone},
            )
            customers.append(customer)

        sample_reviews = [
            ("nimbus-air-buds", 0, 5, "Clear sound and a secure fit for daily use."),
            ("nimbus-air-buds", 1, 4, "Battery lasts a full workday."),
            ("harbor-bass-one", 0, 5, "Bass is even and the cushioning is comfortable."),
            ("voltpack-10k", 1, 4, "Charges a phone twice without getting warm."),
        ]
        for slug, reviewer_index, rating, comment in sample_reviews:
            product = Product.objects.filter(slug=slug).first()
            if not product:
                continue
            Review.objects.update_or_create(
                product=product,
                customer=customers[reviewer_index],
                defaults={"rating": rating, "comment": comment, "is_approved": True},
            )

        removed = ("wearables", "computing", "kitchen")
        Product.objects.filter(category__slug="kitchen").delete()
        SubCategory.objects.filter(category__slug="kitchen").delete()
        Category.objects.filter(slug="kitchen").delete()
        Brand.objects.filter(slug__in=("hearth", "prepkit", "clearkeep")).delete()
        Category.objects.filter(slug__in=("wearables", "computing")).update(is_active=False)
        SubCategory.objects.filter(category__slug__in=("wearables", "computing")).update(is_active=False)
        Product.objects.filter(category__slug__in=("wearables", "computing")).update(is_published=False)

        self.stdout.write(
            self.style.SUCCESS(
                f"Catalog ready: {created} created, {updated} updated, {len(PRODUCTS)} products."
            )
        )
