# Generated by Django 5.2.17 on 2026-09-11 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0004_product_image_upload_and_storefront'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('placement', models.CharField(choices=[('hero', 'Hero'), ('promo', 'Promo'), ('slide', 'Carousel')], max_length=16)),
                ('eyebrow', models.CharField(blank=True, max_length=80)),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='banners/%Y/%m/')),
                ('image_alt', models.CharField(blank=True, max_length=160)),
                ('button_label', models.CharField(blank=True, max_length=80)),
                ('button_url', models.CharField(blank=True, max_length=255)),
                ('secondary_button_label', models.CharField(blank=True, max_length=80)),
                ('secondary_button_url', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['sort_order', '-created_at'],
                'indexes': [models.Index(fields=['placement', 'is_active', 'sort_order'], name='content_ban_placeme_148652_idx')],
            },
        ),
        migrations.CreateModel(
            name='HomepageSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('section_type', models.CharField(choices=[('featured_categories', 'Featured categories'), ('best_sellers', 'Best sellers'), ('new_arrivals', 'New arrivals'), ('featured_products', 'Featured products'), ('category', 'Category products'), ('custom', 'Selected products')], max_length=32)),
                ('eyebrow', models.CharField(blank=True, max_length=80)),
                ('title', models.CharField(max_length=160)),
                ('action_label', models.CharField(blank=True, max_length=80)),
                ('action_url', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='homepage_sections', to='catalog.category')),
                ('products', models.ManyToManyField(blank=True, related_name='homepage_sections', to='catalog.product')),
            ],
            options={
                'verbose_name': 'Homepage section',
                'verbose_name_plural': 'Homepage sections',
                'ordering': ['sort_order', 'id'],
                'indexes': [models.Index(fields=['is_active', 'sort_order'], name='content_hom_is_acti_250a0e_idx')],
            },
        ),
    ]
