export const endpoints = {
  health: "/health/",
  products: "/v1/products/",
  productSuggest: "/v1/products/suggest/",
  categories: "/v1/categories/",
  brands: "/v1/brands/",
  categoryDetail: (slug: string) => `/v1/categories/${slug}/`,
  categorySubcategories: (slug: string) => `/v1/categories/${slug}/subcategories/`,
  productDetail: (slug: string) => `/v1/products/${slug}/`,
  productReviews: (slug: string) => `/v1/products/${slug}/reviews/`,
  register: "/v1/auth/register/",
  login: "/v1/auth/login/",
  logout: "/v1/auth/logout/",
  me: "/v1/auth/me/",
  changePassword: "/v1/auth/change-password/",
  passwordReset: "/v1/auth/password-reset/",
  passwordResetConfirm: "/v1/auth/password-reset/confirm/",
  cart: "/v1/cart/",
  cartQuote: "/v1/cart/quote/",
  cartItems: "/v1/cart/items/",
  cartItem: (id: number) => `/v1/cart/items/${id}/`,
  addresses: "/v1/addresses/",
  address: (id: string) => `/v1/addresses/${id}/`,
  addressValidate: "/v1/addresses/validate/",
  orders: "/v1/orders/",
  orderDetail: (orderNumber: string) => `/v1/orders/${orderNumber}/`,
  wishlist: "/v1/wishlist/",
  wishlistItem: (productId: string) => `/v1/wishlist/${productId}/`,
  paymentConfig: "/v1/payments/config/",
  storeSettings: "/v1/store/settings/",
  staffSettings: "/v1/staff/settings/",
  staffDashboard: "/v1/staff/dashboard/",
  staffOptions: "/v1/staff/options/",
  staffProducts: "/v1/staff/products/",
  staffProduct: (id: string) => `/v1/staff/products/${id}/`,
  staffProductImages: (id: string) => `/v1/staff/products/${id}/images/`,
  staffProductImage: (id: string, imageId: number) => `/v1/staff/products/${id}/images/${imageId}/`,
  staffOrders: "/v1/staff/orders/",
  staffOrder: (orderNumber: string) => `/v1/staff/orders/${orderNumber}/`,
} as const;
