# Generated by Django 5.2.17 on 2026-09-11 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_product_image_url_charfield'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['name'], name='catalog_pro_name_f603c0_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_published', 'name'], name='catalog_pro_is_publ_4ec3dc_idx'),
        ),
    ]
