# Generated by Django 5.2.17 on 2026-09-11 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_product_search_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
            ],
            options={
                'verbose_name': 'Inventory item',
                'verbose_name_plural': 'Inventory',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('catalog.product',),
        ),
        migrations.AddField(
            model_name='productimage',
            name='image',
            field=models.ImageField(blank=True, upload_to='products/%Y/%m/', verbose_name='upload'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='url',
            field=models.CharField(blank=True, help_text='Filled automatically after upload, or paste a public image URL.', max_length=500),
        ),
    ]
